swagger: '2.0'
info:
  title: Rating Control Service
  version: 1.0.0
  contact:
  name: API Service Team
  email: serviceTeam@test.api.com
  url: 'https://www.api-develop-learn.com/help'
  termsOfService: Rating Control Service indicate eligibility
  about book read suitability based on control level set
license:
name: api-test.com
url: 'https://www.api-develop-learn.com/help/articles/testterms-and-conditions'
schemes:
  - https
host: $(catalog.host)
basePath: /rating-control
consumes:
  - application/json
produces:
  - application/json
paths:
  '/rcl/book/v1/read/eligibility/{control_level}/{book_id}':
  get:
  responses:
  '200':
  description: 200 OK
  schema:
  type: boolean
  '400':
  description: Bad Request
  schema:
  $ref: '#/definitions/ErrorResponse'
  '404':
  description: Not Found
  schema:
  $ref: '#/definitions/ErrorResponse'
  '500':
  description: Internal Server Error
  schema:
  $ref: